<?php 
	@define("cafeteria1",  ("Productos"));	
	@define("cafeteria2", ("Nombre"));
	@define("cafeteria3", ("Referencia"));
	@define("cafeteria4", ("Precio"));
	@define("cafeteria5", ("Peso"));
	@define("cafeteria6", ("Categoria"));
	@define("cafeteria7", ("Stock"));
	@define("cafeteria8", ("Fecha"));
	@define("cafeteria9", ("Opciones"));
 	@define("cafeteria10", ("Crear Producto"));
 	@define('cafeteria11',  ('Opciones '));
 	@define('cafeteria12',  ('Editar '));
 	@define('cafeteria13',  ('Eliminar '));
 	@define('cafeteria14',  ('Stock '));
 	@define('cafeteria15',  ('Sin Stock '));
 	@define('cafeteria16',  ('Lista '));
 	@define('cafeteria17',  ('Producto registrar '));
 	@define('cafeteria18',  ('Guardar '));
 	@define('cafeteria19',  ('Exito '));
 	@define('cafeteria20',  ('Registro exitoso '));
 	@define('cafeteria21',  ('Error '));
 	@define('cafeteria22',  ('Ups! '));
 	@define('cafeteria23',  ('Uno o mas campos estan vacios , por favor verifica!! '));
 	@define('cafeteria24',  ('Producto Editar '));
 	@define('cafeteria25',  ('Edicion exitosa'));
 	@define('cafeteria26',  ('Error al editar '));
 	@define('cafeteria27',  ('Error al eliminar '));
 	@define('cafeteria28',  ('Se elimino exitosamente '));
 	@define('cafeteria29',  ('Inicio '));
 	@define('cafeteria30',  ('Comprar '));
 	@define('cafeteria31',  ('Productos '));
 	@define('cafeteria32',  ('Peso : '));
 	@define('cafeteria33',  ('Stock : '));
 	@define('cafeteria34',  ('No hay productos disponobles'));
 	@define('cafeteria35',  ('cantidad'));
 	@define('cafeteria36',  ('La cantidad ingresada es superior al stock actual'));
 	@define('cafeteria37',  ('La cantidad ingresada no puede ser menor o igual a 0'));
 	@define('cafeteria38',  ('Compra exitosa '));
 	@define('cafeteria39',  ('Producto '));
?>